version: '3'

services:
  generate:
    build: .
    volumes:
      - ./protos:/protos
      - ./gen:/gen
    
  generate-csharp:
    image: namely/protoc-all
    volumes:
      - .:/defs
    command: "-d /defs/protos -l csharp"

  generate-node:
    image: namely/protoc-all
    volumes:
      - .:/defs
    command: "--with-typescript -d /defs/protos -l node"

  generate-web:
    image: namely/protoc-all:1.22_0
    volumes:
      - .:/defs
    command: "-d /defs/protos -l web"

  # descriptor & lint & docs
  generate-descriptor-set:
    image: namely/protoc-all
    volumes:
      - .:/defs
    command: "-d /defs/protos -l descriptor_set --descr-include-imports --descr-include-source-info --with-docs markdown,docs.md --lint"